export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const UNSET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const UNSET_ERROR_MESSAGE = 'UNSET_ERROR_MESSAGE';
export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const MAKE_SEARCH = 'MAKE_SEARCH';
export const GET_WORD_DATA = 'GET_WORD_DATA';
